// This file is auto-generated by the `update-kc-gen` command. Do not edit it manually.
// Hash: 3fa678c5ff78db350f5bcc13d65f098f96015fc2f0b8edbd5c3925ba70d54abe

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

import { lazy, Suspense, type ReactNode } from "react";

export type ThemeName = "keycloakify-starter";

export const themeNames: ThemeName[] = ["keycloakify-starter"];

export type KcEnvName = "THEME_FAQ_PAGE";

export const kcEnvNames: KcEnvName[] = ["THEME_FAQ_PAGE"];

export const kcEnvDefaults: Record<KcEnvName, string> = {
  THEME_FAQ_PAGE: "https://www.google.com"
};

/**
 * NOTE: Do not import this type except maybe in your entrypoint.
 * If you need to import the KcContext import it either from src/login/KcContext.ts or src/account/KcContext.ts.
 * Depending on the theme type you are working on.
 */
export type KcContext = import("./login/KcContext").KcContext;

declare global {
  interface Window {
    kcContext?: KcContext;
  }
}

export const KcLoginPage = lazy(() => import("./login/KcPage"));

export function KcPage(props: { kcContext: KcContext; fallback?: ReactNode }) {
  const { kcContext, fallback } = props;
  return (
    <Suspense fallback={fallback}>
      {(() => {
        switch (kcContext.themeType) {
          case "login":
            return <KcLoginPage kcContext={kcContext} />;
        }
      })()}
    </Suspense>
  );
}
